name: carnet_de_voyage
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #go_router pour gestion des routes
  go_router: ^14.2.7

  # Dépendances Firebase (versions compatibles)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1 
  firebase_auth_platform_interface: ^7.4.7
  firebase_auth_web: ^5.13.2
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1
  flutter_facebook_auth: ^7.1.0
  google_sign_in: ^6.0.0
  logger: ^2.4.0
 

  # Cupertino Icons
  cupertino_icons: ^1.0.8

  # SQLite pour la gestion des données locales
  sqflite: ^2.2.8+1
  path_provider: ^2.0.14
  path: ^1.8.3 

  # Google Maps pour l'affichage des cartes
  google_maps_flutter: ^2.2.5

  # QR code scanner (optionnel)
  qr_code_scanner: ^1.0.1

  #interopérabilités 
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true