platform :ios, '14.0'

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  project 'Runner', {
    'Debug' => 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig',
    'Profile' => 'Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig',
    'Release' => 'Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig'
  }

  use_frameworks! :linkage => :dynamic
  use_modular_headers!

  # Ajoute Firebase et Google Maps
  pod 'GoogleMaps', :modular_headers => false

  # Installer toutes les dépendances pour Flutter
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end