name: carnet_de_voyage
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Dépendances Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  # SQLite pour la gestion des données locales
  sqflite: ^2.2.8+1
  path_provider: ^2.0.14

  # Google Maps pour l'affichage des cartes
  google_maps_flutter: ^2.2.5

  # QR code scanner (optionnel)
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true